# Generated by Django 4.2.8 on 2023-12-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('data', models.TextField(verbose_name='Data')),
                ('date', models.DateTimeField(verbose_name='Date')),
            ],
        ),
    ]
